---
title: "Post-Assignment Reflection"
author: "Your Name"
date: "January 15, 2023"
format: html
editor: visual
---

## Reflection Prompts

1.  Highlight one or two things you are especially proud of regarding your submission. This could be a particular element within the assignment or could be part of your process (e.g. time management, applying new techniques, etc.).

I am proud of being able to overcome the learning curve that I was already anticipating with diving back into R for the semester. It's been some years since I've used the program, and even then it was only to a fairly entry-level extent. So being able to complete the tasks of this lab was something I was proud of.

1.  If you were to start this assignment over again, what are one or two things that you might do differently?

I would definitely ask for help sooner. For the most part, I spent a long period of time trying to figure out why my code wasn't working. I was watching YouTube videos and scrolling through forums looking for answers, but using Slack or sending a quick email to Prof Greenlee was much more effective and timely.

1.  Are there any aspects or areas in your submission where you would like us to focus our feedback?

I would like to get some feedback specifically about redundancies or unnecessary aspects in both my code and my directory set up. I want to know if there were things that I did that made things harder for myself or just additional work, or if I can streamline my process in any way.

1.  On a scale of 1 to 10, please rate how ready you feel this work is for sharing with a public audience (where 1 is not at all ready to be shared and 10 is polished and ready for public dissemination). Briefly describe why you gave your work this rating.

I would give myself a 7. Compared to when I gave my first pass on this initial lab, my rating would have been somewhere around a 2, because I wasn't able to complete multiple steps to the Lab because of issues with my setup or code. Now that I was able to fully work my way through those problems, I think I'm more comfortable sharing my work.

Thank you for taking the time to evaluate your efforts. We look forward to sharing feedback with you soon!
